# .github/actions/build-playground/action.yml
name: 'Build Vite Playground'
description: 'Builds Vite playground and uploads as artifact'
inputs:
  node-version:
    description: 'Node version'
    required: false
    default: '21.7.3'
  artifact-name:
    description: 'Artifact name to upload'
    required: false
    default: 'playground-dist'
  base-subpath:
    description: 'Base subpath for the Vite build (e.g., /<repo>/playground/)'
    required: true
  workdir:
    description: 'Playground directory'
    required: false
    default: 'playground'
runs:
  using: 'composite'
  steps:
    # (Checkout is done in the workflow before calling this action)
    - name: Setup PNPM
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Install deps (root)
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Install deps (playground)
      shell: bash
      working-directory: ${{ inputs.workdir }}
      run: pnpm install --frozen-lockfile

    - name: Build playground with normalized base path
      shell: bash
      working-directory: ${{ inputs.workdir }}
      run: |
        BASE="${{ inputs.base-subpath }}"
        # ensure leading slash
        case "$BASE" in /*) ;; *) BASE="/$BASE" ;; esac
        # ensure trailing slash
        case "$BASE" in */) ;; *) BASE="$BASE/" ;; esac
        echo "Building playground with base: $BASE"
        pnpm build -- --base "$BASE"
        # SPA fallback for GitHub Pages
        cp dist/index.html dist/404.html

    - name: Upload playground artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.workdir }}/dist
        if-no-files-found: error
