name: 'Build VitePress Docs'
description: 'Builds VitePress docs and uploads as artifact'
inputs:
  node-version:
    description: 'Node version'
    required: false
    default: '21.7.3'
  artifact-name:
    description: 'Artifact name to upload'
    required: false
    default: 'docs-dist'
runs:
  using: 'composite'
  steps:
    - name: Setup PNPM
      uses: pnpm/action-setup@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
        registry-url: 'https://registry.npmjs.org'

    - name: Install deps
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Build docs (with explicit base for Pages)
      shell: bash
      run: pnpm docs:build
      env:
        BASE_PATH: "/AI-Chat/"

    - name: Upload docs artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: docs/.vitepress/dist
        if-no-files-found: error
