blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/OWNER/REPO/discussions
    about: Please ask and answer questions here.
  - name: Security Reports
    url: https://github.com/OWNER/REPO/security/advisories/new
    about: Please report security vulnerabilities privately.
