name: build-playground
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.7.3
          cache: 'pnpm'

      - name: Install deps (root)
        run: pnpm install --frozen-lockfile

      - name: Install deps (playground)
        working-directory: playground
        run: pnpm install --frozen-lockfile

      - name: Build playground with base path
        working-directory: playground
        run: |
          pnpm build -- --base "/${{ github.event.repository.name }}/playground/"
          cp dist/index.html dist/404.html

      - name: Upload playground artifact
        uses: actions/upload-artifact@v4
        with:
          name: playground-dist
          path: playground/dist
          if-no-files-found: error
