name: pages-deploy

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  docs:
    uses: ./.github/workflows/build-docs.yml

  playground:
    uses: ./.github/workflows/build-playground.yml

  merge-and-deploy:
    runs-on: ubuntu-latest
    needs: [docs, playground]
    steps:
      - name: Download docs
        uses: actions/download-artifact@v4
        with:
          name: docs-dist
          path: site/docs

      - name: Download playground
        uses: actions/download-artifact@v4
        with:
          name: playground-dist
          path: site/playground

      - name: Merge playground into docs site
        run: |
          mkdir -p site/docs/playground
          cp -r site/playground/* site/docs/playground/

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/docs

  deploy:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    needs: merge-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
