# .github/workflows/pages-deploy.yml
name: pages-deploy

on:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build docs
        uses: ./.github/actions/build-docs
        with:
          artifact-name: docs-dist

  build-playground:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build playground
        uses: ./.github/actions/build-playground
        with:
          artifact-name: playground-dist
          base-subpath: "/${{ github.event.repository.name }}/playground/"
          # workdir: 'playground' # change only if your folder name differs

  merge-and-deploy:
    runs-on: ubuntu-latest
    needs: [build-docs, build-playground]
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Download docs
        uses: actions/download-artifact@v4
        with:
          name: docs-dist
          path: site/docs

      - name: Download playground
        uses: actions/download-artifact@v4
        with:
          name: playground-dist
        # we’ll merge into docs folder at /playground
          path: site/playground

      - name: Merge playground into docs site
        run: |
          mkdir -p site/docs/playground
          cp -r site/playground/* site/docs/playground/

      - name: Sanity check output
        run: |
          test -f site/docs/index.html || (echo "index.html missing" && exit 1)
          echo "Deployed root contains:"
          ls -la site/docs | sed -n '1,80p'

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/docs

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
